### ISSUE TITLE
feedback on bald netcdf-ld examples

### ISSUE THREAD

**Issue by VladimirAlexiev** [opengeospatial/netcdf-ld#119]
@marqh @dr-shorthair @nicholascar
Is it relevant to provide feedback on https://binary-array-ld.github.io/netcdf-ld/ examples?
(BTW, where is the source of these examples? Can't find it on https://github.com/binary-array-ld)

Here is some, and I may have more:
- [ ] CDL includes datatypes (eg `valid_min = -1200s`, I guess that means `short`) that are not in Turtle (eg "-1200"). https://github.com/binary-array-ld/netcdf-ld/blob/master/examples/oisst/avhrr-only-v2.19810901_a.ttl includes these letters but within the string value (not ok)
- [ ] Turtle uses prefix `bald: <http://binary-array-ld.net/latest/>`
  but JSON-LD uses `"ncld": "http://binary-array-ld.net/latest/"`
- [ ] IMHO it's not ok to use `this:` as a namespace for common props like `Source minValue creation_date title units scale_factor` etc. Define them in a common `ncld:` ontology (1)
- [ ] These prop names don't conform to naming convention (lcase camelCase): `this:Contact this:Conventions this:History this:Source`
- [ ] IMHO it's better for the prefix `this: <file:///tmp/tmpyt4n_hzw.nc/>` to end in hash not slash, because internal resources are embedded in the file, not separate files in a folder. This way you can also use the prefix for the whole file:
```ttl
@prefix this: <file:///tmp/tmpyt4n_hzw.nc#> .
this: a bald:Container;
  bald:contains this:anom, this:anom_lat_ref...
```
- [ ] In fact I think it's better to use `@base <file:///tmp/tmpyt4n_hzw.nc#>` (JSON-LD also has that) and then:
```ttl
@base <file:///tmp/tmpyt4n_hzw.nc#> .
<> a bald:Container;
  bald:contains <anom>, <anom_lat_ref>...
```

**Comment by marqh** [comment]
@VladimirAlexiev 

thank you for this feedback
it seems clear to us that an editorial mismatch has occurred here, and teh examples presented within
https://binary-array-ld.github.io/netcdf-ld/

are not up to date with respect to the standards work

we need to adopt a different approach for these resources, either building them dynamically, or linking to other managed resources

we will adapt this approach, then look to re-address your detail points with respect to newly published entities

**Comment by VladimirAlexiev** [comment]
hi @marqh! Does the standard come with an official set of examples?
See https://github.com/opengeospatial/netcdf-ld/issues/122 where I've described this a bit better

**Comment by jyucsiro** [comment]
Hi @VladimirAlexiev - examples can be found in 2 spots currently
1. In the specification test suite - https://github.com/opengeospatial/netcdf-ld/tree/master/standard/abstract_tests
2. In the Python Implementation integration tests - https://github.com/binary-array-ld/bald/tree/master/lib/bald/tests/integration

As mentioned by @marqh, examples in https://binary-array-ld.github.io/netcdf-ld/ are very out of date, as they were last updated in 2016. We're in the process of updating that site to reflect current status. We have decided to remove examples from that site as it is an additional location for content drift. 

We are aspiring to have tests (and examples) in the OGC specification test suite that implementations can reference. Over time, more tests/examples may be added to that location.

**Comment by jyucsiro** [comment]
This is now addressed as part of https://github.com/binary-array-ld/netcdf-ld/pull/6
