### ISSUE TITLE
Fill out the text of the terms and definitions

### ISSUE THREAD

**Issue by jyucsiro** [opengeospatial/netcdf-ld#22]
Some terms have been suggested in the clause 4 of the specification. This issue is about filling out the text of the terms and definitions section.

**Comment by jyucsiro** [comment]
PR #23 created.

We had a question about having both RDF statement and triple defined. Decided to pick one and be consistent with the use of that term in the body of the document.

**Comment by jyucsiro** [comment]
Decided to combine `triple` definition into `RDF statement` and note that `triple` is a synonym.

**Comment by jyucsiro** [comment]
Need one for `Broadcast`

**Comment by marqh** [comment]
#29 is the term 'Broadcast' still requiring definition, or is it less used now?

**Comment by marqh** [comment]
closed by #88
