### ISSUE TITLE
Mapping to NCML

### ISSUE THREAD

**Issue by martinjuckes** [opengeospatial/netcdf-ld#25]
Hi, the draft looks excellent. It looks to me as though it would be technically easy to map this into NCML to produce XML files with declared namespaces. Have you considered this option?

**Comment by marqh** [comment]
Hello @martinjuckes 

I haven't looked into mapping this into NCML, I don't know that specification very well.

the process to make declared namespaces is a key facet of this work, so I can understand the potential interest.  However, I don't have a driver for pushing work in this direction at the moment.

thank you for sharing your thoughts
mark

**Comment by jyucsiro** [comment]
Not looking to implement this at this current phase of the activity. Might reopen later if there is more interest.
