### ISSUE TITLE
RDF Terms and Definitions - comments and suggestions.

### ISSUE THREAD

**Issue by skwlilac** [opengeospatial/netcdf-ld#26]
I have few gnit-picky comments and suggestions for the Chapter 4 Terms and Defs wrt to the description of RDF terminology

1. wrt: 4.2 "RDF statements (or triples)" - The second sentence says:
  *"It [a triple] is a set of three entities which codify a statement about semantic data".*
   I suggest this be re-written as:
   *"It [a triple] is used to make a logical statement about the triple's subject (which could be anything)".*
   In particular, RDF in general does not restrict statements to be "...about semantic data" 
   they can be about anything (or at least anything that could be named with a URI).

2. wrt: 4.2 first sentence: I don't think the *"...(or a semantic triple)"* in the first sentence helps. We already have statements and triples as near synonyms - I don't think a 3rd variant helps, certainly I snagged on it. As regards triples and statements, I tend toward a syntactic/semantic distinction in that a triple is the constrained syntactic form used to make a statement whereas the statement is its logical interpretation (which has a truth value) - but there is a whole rabbit hole there to disappear into around interpretations (mappings of URI to things in the world) and RDF model and syntax.

3. wrt: 4.3 "RDF Graph" at the level of this narrative, I suggest changing the last part of the last sentence to *"...while the predicate is used to label the edges...."*. Just as in RDF in general there is some triple/statement duality, there is also some property/predicate duality. The latter is routed in the notion of a logical function, `p(s,o) -> true|false`, a binary predicate, which has an extension that is all the `{s,o}` pairs for which `p` holds true. Anyway that's back on the edge of the rabbit hole. 

4. wrt 4.4 URI  the first sentence says: 
*"A Uniform Resource Identifier (URI) is a string of characters that precisely identify a particular information object."* 
There is no such constraint - URI in general can be used it identify anything - eg. http://dbpedia.org/resource/Elvis_Presley is used to identify the person and global phenomenon that is/was Elvis - indeed the example later focusses on B.B. King.

**Comment by adamml** [comment]
@skwlilac Thanks for the comments.

@jyucsiro, @marqh I'll pick this up and put in a pull request to update the definitions

**Comment by jyucsiro** [comment]
PR created and merged now.
