### ISSUE TITLE
Question on `bald:Subject` 

### ISSUE THREAD

**Issue by skwlilac** [opengeospatial/netcdf-ld#27]
I'm still finding my way around the BALD vocabulary and variable-to-variable referencing (coming from an RDF world rather than a netCDF world). I'm wondering about the role of the class `bald:Subject`.... whether in needs to be any more constrained than `rdfs:Resource`... and if so whether `bald:Resource` would be a better name to avoid possible confusion with subject roles in an RDF triple.

![bald](https://user-images.githubusercontent.com/3800472/67944524-8c7ab000-fbd4-11e9-8796-7b4f57176136.png)

**Comment by marqh** [comment]
Hi @skwlilac 

thank you for the comments

I think that the intent of `bald:Subject` is to identify a generic entity within a binary array file format that is able to act as a subject or object within an RDF graph.  

That is, it has identity and may have statements defined about it and statements which apply to it.

The specific entities, such as `bald:Array` and `bald:Container` are then specialisations of this for more targeted entities, netCDF Variables and netCDF groups in the case of netCDF.

As such, I think that `bald:Resource` seems like a nicer way to define this concept.  It also makes it clearer where is derives from, and suggests the addition of `bald:Resource a rdfs:Resource` in its definition.

@adamml @jyucsiro what do you think?

**Comment by skwlilac** [comment]
`bald:Resource rfds:subClassOf rdfs:Resource` I think?

**Comment by marqh** [comment]
@skwlilac 

yes, you are right, this is a class and subClassOf, not an instance

**Comment by adamml** [comment]
> Hi @skwlilac
> 
> thank you for the comments
> 
> I think that the intent of `bald:Subject` is to identify a generic entity within a binary array file format that is able to act as a subject or object within an RDF graph.
> 
> That is, it has identity and may have statements defined about it and statements which apply to it.
> 
> The specific entities, such as `bald:Array` and `bald:Container` are then specialisations of this for more targeted entities, netCDF Variables and netCDF groups in the case of netCDF.
> 
> As such, I think that `bald:Resource` seems like a nicer way to define this concept. It also makes it clearer where is derives from, and suggests the addition of `bald:Resource a rdfs:Resource` in its definition.
> 
> @adamml @jyucsiro what do you think?

I'm happy with `bald:Resource rdfs:subClassOf rdfs:Resource`

**Comment by jyucsiro** [comment]
Sounds good to me. Agree with the reason for `bald:Resource rdfs:subClassOf rdfs:Resource`. Thanks @skwlilac

**Comment by jyucsiro** [comment]
Propose we close this issue as we have settled on `bald:Resource` now.
