### ISSUE TITLE
Choice of property for alias declarations

### ISSUE THREAD

**Issue by der** [opengeospatial/netcdf-ld#28]
The specification includes an alias mechanism to map attributes names to RDF predicates. These alias mappings are supplied to a netCDF-LD processor as RDF declarations. Section 6.3.4 proposes use of `dct:identifier` for this purpose. So an alias declaration looks like:

    myns:meaningfulPredicate a rdf:Property; dct:identifier 'attributeName' .

Would it be better to use a separate property defined within the specification (e.g. `bald:alias`) rather than repurposing `dct:identifier`?

Logging this as an issue is intended to simply give a place where the question can be discussed, not to indicate any fundamental problem with the current approach.

## Framing discussion

There are a number of considerations here:

This is certainly a reasonable choice. This usage is consistent with the meaning of `dct:identifer` and `dct` is a widely accepted vocabulary. 

The meaning of `dct:identifier` is broader than it's usage here so, arguably, a more specific term such as `bald:alias` would enable a publisher to more clearly signal that such a declaration was intended to introduce a netCDF-LD alias rather than anything else. Indeed `bald` could formally state:

    bald:alias rdfs:subPropertyOf dct:identifier .

In a closed world in which the configuration file supplied to the netCDF processor is self-contained and under full control of the processing agent then the choice of identifier is largely arbitrary. 

If a goal is to encourage communities to publish and maintain vocabularies of terms that can be used in netCDF files and support semantic mapping then the choice might make a difference. 

On the one hand, if a publisher already includes `dct:identifier` declarations for other reasons then this may cause issues. A processing agent taking that vocabulary as part of the input to a netCDF-LD run would need to modify it to remove any clashing or inappropriate mappings which would otherwise be unintentionally treated as aliases. Since RDF is purely additive it is easier to add missing aliases (e.g. via a supplemental mapping file) than it is to suppress unintended aliases caused by differing uses of of `dct:identifier`. 

On the other hand, in approaching a publisher to ask them to supplement a vocabulary with aliases for netCDF use then it may be easier to persuade them to use a common and well known term than to persuade them to adopt the currently-unknown `bald`.

**Comment by marqh** [comment]
thank you for sharing your thoughts @der 

I think that one perceived advantage of using `dct:identifier` is promoting the reuse of established vocabularies for publishers of netCDF convention specification vocabularies.  There is some benefit to showing publishers, such as Unidata, that the netCDF vocabulary can be defined without using the `bald` terms.

However, there are places where we have specified the use of the `bald` vocabulary, specifically, for defining `rdf:Property` instances that represent explicit references, we have required that the entity define an `rdfs:range` of `bald:Subject` (or resource? #27) to enable the variable to variable referencing to be managed.

```
<entity>
        a                rdf:Property ;
        rdfs:range       <http://binary-array-ld.net/latest/Subject> ;
```

Given this case, I am now more relaxed about defining a new `bald` term
```
bald:alias rdfs:subPropertyOf dct:identifier .
```
and using this to make alias definition more closely related to `bald`.

The last paragraph in @der 's analysis highlights why this may be a slightly more limiting approach, and I'm interested in discussing the merits of each course of action.

@jyucsiro @adamml

**Comment by adamml** [comment]
@der @marqh This is an interesting topic for discussion, and I think one which needs careful consideration.

As can be seen in @der's comment and in @marqh's response, there are pros and cons to both approaches.

However, I think the pros of the `bald:alias` approach probably outweigh the cons, and perhaps this is something we should discuss in further detail.

**Comment by jyucsiro** [comment]
After a bit of conversation, I actually think the pros of a vanilla `dct:identifier` would suffice. 

> On the other hand, in approaching a publisher to ask them to supplement a vocabulary with aliases for netCDF use then it may be easier to persuade them to use a common and well known term than to persuade them to adopt the currently-unknown bald.

> I think that one perceived advantage of using dct:identifier is promoting the reuse of established vocabularies for publishers of netCDF convention specification vocabularies. There is some benefit to showing publishers, such as Unidata, that the netCDF vocabulary can be defined without using the bald terms.

These 2 were the main reasons. 

Also a bit wary of introduce additional semantics where there is arguably marginal gain vs. the alternative, which is to simply promote reuse of an established practice. I do agree that the semantics of `bald:alias` is more precise. The tradeoff is that may be additional overhead, and potential friction in adopting this vs. the established `dct:identifier` which currently serves the purpose, which is to denote an identifier for the alias.

**Comment by jyucsiro** [comment]
propose we close this issue as it seems we have settled on `dct:identifier` which is referred to in the spec now.
