### ISSUE TITLE
isPrefixedBy to external resource

### ISSUE THREAD

**Issue by marqh** [opengeospatial/netcdf-ld#36]
Feedback from adopters has revealed some unwanted effects from the definition of prefixes within a file.

With a netCDF classic file the prefixes may only be stored as a variable.

However, a variable carries data, which may be missing, but is still an oddity for a metadata only element.

NetCDF software is prone to read this variable and assume that it is a content data variable and present it to users.

With this in mind, it is proposed that the external mechanism used for alias definitions is extended to enable the definition of prefixes external to the netCDF file.

In this way, a file can use prefixed entities, but resolve them using a remote resource to provide the predicate URIs

This proposal reduces the self-describing nature of the file somewhat.

This proposal reduces an obstruction to adoption for users and makes the netCDF files simpler and easier to manage.

The namespace functionality of the prefixed attribute and value remains intact.

**Comment by marqh** [comment]
@jyucsiro 

Hi Jonathan

I shared your proposal with my colleagues who fed back on this issue, to enable externalised prefix definitions.

Their verbal feedback was quite positive for this proposal
@TomekTrzeciak  
@bjwheltor

**Comment by marqh** [comment]
@adamml 

consider vocabulary that we could use to explicitly define prefix and URI

e.g. https://vocab.org/vann/

**Comment by marqh** [comment]
@jyucsiro 

consider use of JSON-LD context

e.g. https://opengeospatial.github.io/ELFIE/contexts/elfie-2/sosa.jsonld

**Comment by adamml** [comment]
Following on from @jyucsiro's comment about JSON-LD, I wondered about how this would work as a TTL encoding. However, there's a handy hint a the W3C's JSON-LD Vocabulary page.

How does the following work for people?

```ttl
@prefix bald: <https://www.opengis.net/def/binary-array-ld/>.
@prefix json-ld: <http://www.w3.org/ns/json-ld#>.

_:0 a bald:Container;
	bald:isPefixedBy [ a json-ld:Context;
	json-ld:version 1.1;
		json-ld:definition [
			a json-ld:PrefixDefinition;
			json-ld:term "bald__";
			json-ld:iri <http://binary-array-ld.net/latest/>
		], [
			a json-ld:PrefixDefinition;
			json-ld:term "rdf__";
			json-ld:iri <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
		], [
			a json-ld:PrefixDefinition;
			json-ld:term "rdfs__";
			json-ld:iri <http://www.w3.org/2000/01/rdf-schema#>
		]
	].
```

**Comment by adamml** [comment]
This should work for an external resource:

```ttl
@prefix bald: <https://www.opengis.net/def/binary-array-ld/>.

_:0 a bald:Container;
    bald:isPefixedBy <http://example.org/a-json-ld-context>
```
The external resource as JSON-LD

```yaml
{
  "@context": {
    "bald": "http://binary-array-ld.net/latest/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#"
  }
}
```

Or as TTL:

```ttl
@prefix json-ld: <http://www.w3.org/ns/json-ld#>.
<http://example.org/a-json-ld-context> a json-ld:Context;
    json-ld:version 1.1;
    json-ld:definition [
        a json-ld:PrefixDefinition;
        json-ld:term "bald";
	json-ld:iri <http://binary-array-ld.net/latest/>
    ], [
	a json-ld:PrefixDefinition;
	json-ld:term "rdf";
	json-ld:iri <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    ], [
	a json-ld:PrefixDefinition;
	json-ld:term "rdfs";
	json-ld:iri <http://www.w3.org/2000/01/rdf-schema#>
   ].
```

But we still need to think how it will work at the group level...

**Comment by jyucsiro** [comment]
This is a blocker to #42. We should move this to the top of the discussion so as to progress the other issues.

**Comment by jyucsiro** [comment]
Just revisiting this again. 

I think we were good with the proposal of using JSON-LD context files as an external file to capture and refer to prefixes. I recall discussion about enabling ncld implementations to provide options to resolve clashes in case there were inline prefixes and external prefixes. They could either be JSON-LD files or TTL style it appears from what @adamml suggests.

I think the draft spec already captures this. Propose we close this issue then as it appears to be resolved.
