### ISSUE TITLE
Smooth out section 6.5.2 Identity

### ISSUE THREAD

**Issue by jyucsiro** [opengeospatial/netcdf-ld#40]
Distinguish between local identity and explicit identity (url). We make the point that each netCDF file has an identity but then refer to explicit identity (URI/URL )in the informative text, whereas in the normative text, we use identity a bit ambiguously. 

Propose we be deliberate and qualify the specific identity being referred to.

See #39

**Comment by jyucsiro** [comment]
| Informative | Normative | Issue | 
|----|----|---|
| 6.5.2. ... If no identity is provided, a default identity, a local file URI, will be used. A local file URI will always use the '/' forward slash as a separator, even on systems where local identifiers use back slash separators. | 7.1.1. ... If no identity is provided, then the path used by a library to access the file is used as a default identity. If used, a local file URI will always use the '/' forward slash as an element separator, even on systems where local identifiers use back slash separators.  |  | 
| The identity is the identity of the root group, the base entity within the netCDF file. This is the identity of the contents of the file. For this reason, this standard mandates that the identifier string will always terminate in a '/' character separator. In this way the root group is identified and is recognised as a conceptual entity identifiably different from the file itself.  |  The identity of the root group shall always terminate in a '/' character. | | 
| Each variable within that file has its own identity, defined relative to the file identity. This is defined using the variable name appended to the file identity and separated by a /. | Each netCDF variable within the root group shall take its identity as a URI, relative to the file identity. This identity is defined using the full variable name, including any owning groups, appended to the file identity. All element separation uses the / character.| | 
| The identity is conceptually distinct from the resolvable location of a file. This may be simply invovlde the appending of a '/' character to the location, but it can be more distinct. | | Spelling... also, no requirements for download URL - do we need some? |

**Comment by simonoakesepimorphics** [comment]
@marqh 
The informative text implies that the NetCDF file and its root group are separate resources (assuming one contains the other), but the normative examples treat them as if they are the same. This is the main place where my implementation currently differs from the normative examples so wanted to draw attention to this.
