### ISSUE TITLE
Prefix section

### ISSUE THREAD

**Issue by jyucsiro** [opengeospatial/netcdf-ld#42]
Prefix section disrepencies?

| Informative | Normative | Comments | 
| --- | --- | --- |
|  | 7.2.1. Requirement B-1. Prefixes defined within a prefix variable shall be used as the definitive list of prefixes for that file | What about if we have an external file defining the prefixes? |
|The 'double underscore' character pair: __ is used as an identifier and as the termination of the prefix; the double underscore is part of the prefix.  |A prefix attribute name, defined in a prefix variable, shall use the limited character set: [a-zA-z0-9_] <br/> <br/> A prefix attribute name, defined in a prefix variable, shall end with the sub-string:__| Not mentioned in informative. Should B-2 be split out to 2 different requirements? | 

Section on `Externally Defined Prefixes` need requirements defined. Also an example of how Externally Defined Prefixes should be included, i.e. using the proposed VANN vocabulary. Also, were we going to evaluate the viability of json-ld style prefixes/context files? see https://opengeospatial.github.io/ELFIE/json-ld/

Refer to #39

**Comment by jyucsiro** [comment]
see discussion at #36

**Comment by marqh** [comment]
closed by #47
