### ISSUE TITLE
New Requirements section for Attribute Values?

### ISSUE THREAD

**Issue by jyucsiro** [opengeospatial/netcdf-ld#45]
6.5.8. Attribute values map to Requirement E-2 in Section 7.5.2. Should this be a new Requirements class to match the subsections in section 6? Took me a little while to find the matching requirement from the informative to the normative sections.

Similarly for 6.6. Dimensions

Refer to #39

**Comment by marqh** [comment]
i've looked into the flow of this again, aware that this ticket is from a while ago

i feel that the flow of normative requirements in section E is quite important, and i would rather keep this as is, raht than break out a new requirements class
