### ISSUE TITLE
add a schema.org worked example in the informative section

### ISSUE THREAD

**Issue by jyucsiro** [opengeospatial/netcdf-ld#46]
Based on #34 and other discussions around schema.org, it would be good to add a worked example of using schema.org in the informative section.

**Comment by jyucsiro** [comment]
@adamml

**Comment by marqh** [comment]
I think there is a valid conversation to address to consider whether the use of schema.org should be part of the specifications for all uses.  Having an example is a good start, but I don't think I'm confident on whether schema.org adds value everywhere, and should be mandated, or whether its an optional enhancement.

We could also consider trying to make semantic links within the bald vocabulary to assist with this.
