### ISSUE TITLE
Variable references - RDF property range inconsistency and sub-classes

### ISSUE THREAD

**Issue by simonoakesepimorphics** [opengeospatial/netcdf-ld#56]
Requirements class [E-1](http://docs.opengeospatial.org/DRAFTS/19-002.html#_requirement_e_1) requires the range of an RDF property to be `bald:Subject` (or a sub-class of), however section [6.5.7](http://docs.opengeospatial.org/DRAFTS/19-002.html#_variable_to_variable_references) requires the range to be `bald:Resource` (or a sub-class of).
Which one is correct?

On a related note, the spec explicitly permits the use of direct sub-classes of the required class, but doesn't mention the need to support indirect sub-classes, eg. `<classA> rdfs:subClassOf <classB> . <classB> rdfs:subClassOf bald:Subject .`, which seems like an equally valid case (note - implementation should guard against circular hierarchies).

**Comment by marqh** [comment]
This is an editorial error.

the document and vocabulary was updated on advice, such the subject was never used.  The correct term is `bald:Resource`, it is always wrong to state ~~`bald:Subject`~~

this ticket shall stay open until closed by a PR

thank you Simon @simonoakesepimorphics

**Comment by marqh** [comment]
the indirect sub-classes, with not on circular hierarchies shall be added as well
