### ISSUE TITLE
Specification of dimensional variable references

### ISSUE THREAD

**Issue by simonoakesepimorphics** [opengeospatial/netcdf-ld#58]
Note - some of this is subjective, from my POV as someone who is not very familiar with NetCDF features, so just a suggestion.

Section [6.6.3](http://docs.opengeospatial.org/DRAFTS/19-002.html#_variable_references_and_dimensions) describes the requirements for _"variable reference between variables defined with respect to netCDF dimensions"_, however at this point it's not clear what that terminology actually means. It's later clarified in section [6.6.4](http://docs.opengeospatial.org/DRAFTS/19-002.html#_netcdf_coordinate_variables) that coordinate variables are an example of such a reference, but it's not clear whether they are the only examples that are expected to be supported by NetCDF-LD, or if there are others that are not explicitly mentioned. I think it would be clearer to define the concept of coordinate variables (and any other dimensional variable references) before 6.6.3, and then to give simple examples of the expected representation of those references in 6.6.3.

When describing reference entities, the section contains the following statements:
* The <$referenceEntity> may define a bald:sourceShape, where that source shape is required to be different from the defining shape of the source array.
* The <$referenceEntity> shall define a bald:sourceShape, whether that source shape is required to be different from the defining shape of the source array or whether the shape is the same.

which seem to be either contradictory or redundant.

The worked example [6.6.5](http://docs.opengeospatial.org/DRAFTS/19-002.html#_worked_example) doesn't appear to implement the requirements described in 6.6.3, despite containing dimensional variable references. It includes the shapes of the variables as described at the beginning of [6.6](http://docs.opengeospatial.org/DRAFTS/19-002.html#_netcdf_dimensions), and the resolution of explicit `bald__references` attributes through prefix expansion and variable location, but does not include any inference of `bald:references` relationships or any shape / reshape descriptions.

**Comment by jyucsiro** [comment]
Looks like this issue was addressed by an implementation. Should we close this one @marqh ?

**Comment by marqh** [comment]
i think this is addressed by #76 and #78 and #81 

@simonoakesepimorphics please reopen this if there are outstanding issues
