### ISSUE TITLE
Attribute value prefix mapping

### ISSUE THREAD

**Issue by simonoakesepimorphics** [opengeospatial/netcdf-ld#82]
Section [6.5.8](http://docs.opengeospatial.org/DRAFTS/19-002.html#_attribute_values) states that "A parsing process shall map attribute values to URIs using identified prefixes first", however the conformance class [A.2.1](http://docs.opengeospatial.org/DRAFTS/19-002.html#_requirement_1_2) implies that the attribute value "rdfs__label" with the prefix "rdfs" being defined should be evaluated as "rdfs__label", ie. without prefix mapping.

Is this an inconsistency in the spec, and if so which version is correct?

**Comment by marqh** [comment]
this is a clear error in A.2.1  the prefix resolution has not resolved properly in the output

this should absolutely be `rdfs:label`

I'll update with a PR

**Comment by simonoakesepimorphics** [comment]
The error is repeated in A4.
