### ISSUE TITLE
Property alias inconsistency

### ISSUE THREAD

**Issue by simonoakesepimorphics** [opengeospatial/netcdf-ld#83]
Section [6.5.6](http://docs.opengeospatial.org/DRAFTS/19-002.html#_attribute_names) states that "An attribute name shall be mapped to an alias URI if, and only if, there is an exact match for the full attribute name as a dct:identifier for an entity within the alias graph".

Conformance class [A.3](http://docs.opengeospatial.org/DRAFTS/19-002.html#_conformance_class_c_aliasing) implies that the attribute name "title" should be aliased to "https://raw.githubusercontent.com/opengeospatial/netcdf-ld/v0.1/standard/abstract_tests/aliases/NetCDF.ttl/title", however the alias file contents describe the resource "http://def.scitools.org.uk/NetCDF/title" as having the dct:identifier "title".

I think this is the same inconsistency that is discussed [here](https://github.com/binary-array-ld/net.binary_array_ld.bald/issues/41#issuecomment-871223184).

**Comment by marqh** [comment]
i agree, I think this an an error

i think that the alias resolution of `title` should result in `http://def.scitools.org.uk/NetCDF/title` not ~~`https://raw.githubusercontent.com/opengeospatial/netcdf-ld/v0.1/standard/abstract_tests/aliases/NetCDF.ttl/title`~~

i'll prepare a PR to this effect

**Comment by simonoakesepimorphics** [comment]
FYI the error is repeated in A4.
