### ISSUE TITLE
Media type inconsistency

### ISSUE THREAD

**Issue by simonoakesepimorphics** [opengeospatial/netcdf-ld#84]
Section [6.5.2](http://docs.opengeospatial.org/DRAFTS/19-002.html#_download_url) of the spec defines the media type of a distribution of a netCDF file to be a `dct:MediaType`, however conformance class [A.1.2](http://docs.opengeospatial.org/DRAFTS/19-002.html#_requirement_2) requires the media type on the distribution to be a `dcat:MediaType` instead. I assume this is a typo since [DCAT](https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_media_type) doesn't define the latter and states that the range of `dcat:mediaType` should be `dct:MediaType`.

This is the case for all of the conformance classes and the worked examples in [section 6](http://docs.opengeospatial.org/DRAFTS/19-002.html#_netcdf_coordinate_variables).

**Comment by marqh** [comment]
i agree, this looks like an encoding error

i'll prepare a PR to alter instances of ~~`dcat:MediaType`~~ to `dct:MediaType`
