### ISSUE TITLE
Variable reference bald:references

### ISSUE THREAD

**Issue by simonoakesepimorphics** [opengeospatial/netcdf-ld#85]
In conformance class [A.5](http://docs.opengeospatial.org/DRAFTS/19-002.html#_conformance_class_e_variable_to_variable_referencing_class_f_coordinate_variables) and worked example [6.6.5](http://docs.opengeospatial.org/DRAFTS/19-002.html#_worked_example), the `bald__references` attribute on `list_collection` and `set_collection` is resolved as if it is a resource-valued property (ie. its values are resolved as links to variables), however no alias file containing a description of `bald:references` is given, and those variables don't have a "shape" from which to construct a `bald:Reference`. Is `bald:references` a special case and is there a part of the spec that describes this behaviour?

**Comment by marqh** [comment]
`bald__references` is defined with respect to the `bald__` prefix, declared vis `bald__isPrefixedBy`

This prefix is expected to enable identification of the fact that `bald:references` is a resouce-valued property

hence it is not required to also include this within an alias file

**Comment by simonoakesepimorphics** [comment]
I don't follow - the prefix lets us know that `bald__references` is the same as `bald:references`, but how do we determine that it's a resource valued property? In the example it looks like the property satisfies condition 1 and 2 described in [6.5.8](http://docs.opengeospatial.org/DRAFTS/19-002.html#_attribute_values), but not condition 3.

**Comment by marqh** [comment]
i think that, according to
https://raw.githubusercontent.com/opengeospatial/NamingAuthority/master/incubation/binary-array-ld/binary-array-ld.ttl

```
<https://www.opengis.net/def/binary-array-ld/references>
        rdfs:range       <https://www.opengis.net/def/binary-array-ld/Reference> .

<https://www.opengis.net/def/binary-array-ld/Reference>
        rdfs:subClassOf  <https://www.opengis.net/def/binary-array-ld/Resource> .
```

The attribute name entity (`bald:references`) declares an `rdfs:range` of `bald:Reference` which declares itself an `rdf:subClassOf` `bald:Resource`.

So, this example is intended to satisfy all 3 conditions.

**Comment by simonoakesepimorphics** [comment]
OK, in that case I think it would be helpful to add something to the spec to say that the schema you linked should be referenced when resolving properties.

**Comment by marqh** [comment]
this makes sense

do you have any suggestions about how / where to add this?

would it be useful within the prefix definition section?
or is it more useful within the variable to variable references?

is it valuable to have this within the normative content?

Is the expectation that all prefix definitions should be resolved and the published content included in the resolving of properties for variable to variable references

do you have any suggestions / reflections @simonoakesepimorphics ?

**Comment by simonoakesepimorphics** [comment]
> do you have any suggestions about how / where to add this?
would it be useful within the prefix definition section?
or is it more useful within the variable to variable references?

I would consider the schema to be effectively equivalent to an alias file that is automatically added to the LD context. As an alias file it can provide both property aliases (of which it currently doesn't have any but that shouldn't be a problem) and property definitions (which gives us information that bald:references and a few others are resource-valued properties). So overall it would seem appropriate to add it to the variable to variable reference section.

> is it valuable to have this within the normative content?

I suppose this is already in the normative content since the expected result in A5 depends on it. 

> Is the expectation that all prefix definitions should be resolved and the published content included in the resolving of properties for variable to variable references

Assuming that published content here means the published schema (sorry if I've misunderstood your wording):
In the A5 example, the `bald` prefix is already given by the `prefix_list ` group, so there's no need to refer to the BALD schema in order to obtain it. I don't think there is much advantage in using the schema to obtain prefixes.
With respect to V2V references, I inferred from [this comment](https://github.com/opengeospatial/netcdf-ld/issues/85#issuecomment-882677817) that we intend to use the schema in all cases by default. I'm fine with this approach but it could work equally well if the user specifically supplied the link to that file as an alias definition.
