### ISSUE TITLE
Revise paragraph 3 of Clause 2

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/netcdf-ld#90]
Clause 2: The third paragraph needs a complete rewrite. The section makes reference to Annex B, but Annex B is empty. There are instances of TBD. A blank line should be placed above the first bullet point so that asciidoctor recognises the text as a bullet list.

**Comment by adamml** [comment]
@jyucsiro and I discussed this and will address #94, #95, #96 and #97 together with this.
