### ISSUE TITLE
URIs of Requirements Classes and Requirements

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/netcdf-ld#93]
In Clause 5.1, complete the URI presented there. It is the base from which the URIs of Requirements are derived.

In Clause 7.1, on the URIs of Requirements Classes, replace 19-002 with the acronym of the spec (presumably **netcdf-ld**). Replace **m.n** with the version number of this specification. 

Also in Clause 7, several requirements (e.g. E-6, E-7) have a + underneath the requirement identifier. This plus sign should be removed.

**Comment by jyucsiro** [comment]
Should the URI be something like: http://www.opengis.net/spec/netcdf-ld/1.0 ?

`1.0` being the version we will be targetting. Otherwise, should it be aligned with the tagged release?

**Comment by ghobona** [comment]
It should be 1.0

**Comment by marqh** [comment]
fixed by #101
